#[Info]
site_name: 勤工助学IT部文档（Beta）
repo_name: itdep-ecust.github.io
repo_url: https://github.com/ITdep-Ecust/itdep-ecust.github.io
site_author: IT-dep in qinban, ECUST.
#[Navigation]
nav:
  - 本项目和仓库相关:
    - 须知: index.md
    - 关于项目: readme.md
    - 贡献方法和规范: 本项目和仓库相关/贡献方法和规范.md
  - 勤工助学官网:
    - 关于官网: 勤工助学官网/README.md
  - 爱心屋线上平台:
    - 关于爱心屋: 爱心屋线上平台/README.md
    - 爱心屋维护: 爱心屋线上平台/maintenance/readme.md
    - 爱心屋部署: 爱心屋线上平台/deploy/readme.md
  - 基础技术文档:
    - 关于基础技术文档: 基础技术文档/README.md

#[UI]
theme:
  name: material
  language: zh  # 界面语言
  favicon: asserts/images/ITLogo.ico  # 网站图标
  logo: asserts/images/qzzxLogo-L.jpg  # 导航栏 Logo
  palette:
    #primary: blue grey
  
    - scheme: default # 日间模式
      primary: grey # 上方的
      accent: cyan # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: black 
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  font:
    text: Roboto  # 正文字体
    code: Roboto Mono  # 代码字体
  icon:
    repo: fontawesome/brands/github  # 仓库图标
    admonition:
      note: octicons/tag-16
      tip: octicons/light-bulb-16
  features:
    - navigation.tabs  # 顶部标签式导航
    - navigation.sections  # 侧边栏按节分组
    - navigation.top  # 回到顶部按钮
    - search.suggest  # 搜索建议
    - search.highlight  # 搜索结果高亮
    - content.tabs.link  # 内容标签页链接
markdown_extensions:
  - admonition
  - pymdownx.details
  - abbr
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - pymdownx.tasklist #复选框支持
  - pymdownx.arithmatex:  # latex支持
      generic: true
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
      auto_title: true # 显示编程语言名称
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - meta # 支持Markdown文件上方自定义标题标签等
extra_css:
  - asserts/css/extra.css
extra_javascript:
  - asserts/js/extra.js
  
extra:
  generator: false  #删除页脚显示“MkDocs”
copyright: Copyright &copy; ITdep in Qinban, Ecust. 内容采用CC-BY-NC-SA 4.0协议. # 左下角的版权声明